org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official

# Unity library integration properties.
# Required by libs/unityLibrary/build.gradle (buildIl2Cpp task and Android resources).
unityStreamingAssets=
unity.installInBuildFolder=false
unity.androidSdkPath=C:/Program Files/Unity/Hub/Editor/6000.6.3f1/Editor/Data/PlaybackEngines/AndroidPlayer/SDK
unity.androidNdkPath=C:/Program Files/Unity/Hub/Editor/6000.6.3f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK